version: '3.1'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: usr
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data